export const data = [
    {id: 1, name: 'Nguyễn Văn A', dateOfBirth: '28/02/1990', email: 'nvana@gmail.com', address: 'Ba Đình, Hà Nội', status: true},
    {id: 2, name: 'Trần Thị B', dateOfBirth: '15/07/1985', email: 'ttb@gmail.com', address: 'Cầu Giấy, Hà Nội', status: false},
    {id: 3, name: 'Lê Văn C', dateOfBirth: '03/10/2000', email: 'lvc@gmail.com', address: 'Hai Bà Trưng, Hà Nội', status: false},
    {id: 4, name: 'Phạm Thị D', dateOfBirth: '20/05/1995', email: 'ptd@gmail.com', address: 'Hoàn Kiếm, Hà Nội', status: true},
    {id: 5, name: 'Ngô Văn E', dateOfBirth: '12/11/1988', email: 'nve@gmail.com', address: 'Cầu Giấy, Hà Nội', status: true},
    {id: 6, name: 'Nguyễn Văn F', dateOfBirth: '28/02/1990', email: 'nvfna@gmail.com', address: 'Ba Đình, Hà Nội', status: true},
    {id: 7, name: 'Trần Thị G', dateOfBirth: '15/07/1985', email: 'ttg@gmail.com', address: 'Cầu Giấy, Hà Nội', status: false},
    {id: 8, name: 'Lê Văn H', dateOfBirth: '03/10/2000', email: 'lvh@gmail.com', address: 'Hai Bà Trưng, Hà Nội', status: false},
    {id: 9, name: 'Phạm Thị I', dateOfBirth: '20/05/1995', email: 'pti@gmail.com', address: 'Hoàn Kiếm, Hà Nội', status: true},
    {id: 10, name: 'Ngô Văn J', dateOfBirth: '12/11/1988', email: 'nvj@gmail.com', address: 'Cầu Giấy, Hà Nội', status: true},
    {id: 11, name: 'Nguyễn Văn K', dateOfBirth: '28/02/1990', email: 'nvk@gmail.com', address: 'Ba Đình, Hà Nội', status: true},
    {id: 12, name: 'Trần Thị L', dateOfBirth: '15/07/1985', email: 'ttl@gmail.com', address: 'Cầu Giấy, Hà Nội', status: false},
    {id: 13, name: 'Lê Văn M', dateOfBirth: '03/10/2000', email: 'lvm@gmail.com', address: 'Hai Bà Trưng, Hà Nội', status: false},
    {id: 14, name: 'Phạm Thị N', dateOfBirth: '20/05/1995', email: 'ptn@gmail.com', address: 'Hoàn Kiếm, Hà Nội', status: true},
    {id: 15, name: 'Ngô Văn O', dateOfBirth: '12/11/1988', email: 'nvo@gmail.com', address: 'Cầu Giấy, Hà Nội', status: true},
    {id: 16, name: 'Nguyễn Văn P', dateOfBirth: '28/02/1990', email: 'nvp@gmail.com', address: 'Ba Đình, Hà Nội', status: true},
    {id: 17, name: 'Trần Thị Q', dateOfBirth: '15/07/1985', email: 'ttk@gmail.com', address: 'Cầu Giấy, Hà Nội', status: false},
    {id: 18, name: 'Lê Văn R', dateOfBirth: '03/10/2000', email: 'lvr@gmail.com', address: 'Hai Bà Trưng, Hà Nội', status: false},
    {id: 19, name: 'Phạm Thị S', dateOfBirth: '20/05/1995', email: 'pts@gmail.com', address: 'Hoàn Kiếm, Hà Nội', status: true},
    {id: 20, name: 'Ngô Văn T', dateOfBirth: '12/11/1988', email: 'nvt@gmail.com', address: 'Cầu Giấy, Hà Nội', status: true}
]